### ISSUE TITLE
게임박스 개별 API 500 에러

### ISSUE THREAD

**Issue by chadireoroonu** [haeundae-triangle/hongsam-BE#6]
개별 게임박스(플레이리스트) 정보 조회 API 요청 시 500에러가 발생합니다.
모든 게임박스에서 동일하게 에러가 발생합니다.

**Comment by nayeonxkim** [comment]
http://43.202.235.15:8000/api/games/servicePlaylist/1/

**Comment by nayeonxkim** [comment]
django 서버 - mysql 서버 간에 동기화가 안되어있었습니다.
Game 테이블과 Playlist 테이블을 묶어주는 Game_Playlist 테이블이 mysql에 반영되어있지 않아서 수동으로 추가해주었습니다!

**Comment by chadireoroonu** [comment]
정상 작동 확인했습니다!
