### ISSUE TITLE
개별게임 상세 정보 요청 API : 3번 게임 에러 발생 

### ISSUE THREAD

**Issue by chadireoroonu** [haeundae-triangle/hongsam-BE#7]
3번게임 상세정보 api 요청 시, 500에러가 발생합니다.
다른 번호의 게임들은 잘 작동합니다.

**Comment by nayeonxkim** [comment]
http://43.202.235.15:8000/api/games/3/
- 3번 데이터가 DB에서 유실되었었습니다ㅠ 새로 인입하여 정상작동 확인했습니다! 이슈닫겠습니다.
